"""add num

Revision ID: 08ec58a25884
Revises: ec9a543004e6
Create Date: 2026-04-19 12:47:28.449049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ec58a25884'
down_revision = 'ec9a543004e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewopenobjectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_reviews', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewopenobjectives', schema=None) as batch_op:
        batch_op.drop_column('number_reviews')

    # ### end Alembic commands ###
