"""fix

Revision ID: 0fd7702b9eb1
Revises: e90014e2126f
Create Date: 2026-01-15 07:02:23.627623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd7702b9eb1'
down_revision = 'e90014e2126f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_leader_admin_feedbacks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_leader_admin_feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], name=op.f('team_leader_admin_feedbacks_admin_review_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_leader_admin_feedbacks_pkey')),
    sa.UniqueConstraint('admin_review_id', name=op.f('team_leader_admin_feedbacks_admin_review_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
