"""add department

Revision ID: 10bf2548a6c2
Revises: 4cc00415a389
Create Date: 2026-01-16 01:19:26.111215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bf2548a6c2'
down_revision = '4cc00415a389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['department'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
