"""add message

Revision ID: 1d1b5fe98b4f
Revises: 885a49552517
Create Date: 2026-04-14 16:16:46.520791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1b5fe98b4f'
down_revision = '885a49552517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('admin_objective_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_objective_id'], ['admin_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
