"""make nit nullable

Revision ID: 247ce252dce3
Revises: 45b20da64cb3
Create Date: 2026-01-16 02:17:38.137796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247ce252dce3'
down_revision = '45b20da64cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
