"""ini

Revision ID: 35832c68ed40
Revises: 9dd4a87b48b2
Create Date: 2026-01-14 16:01:24.904417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35832c68ed40'
down_revision = '9dd4a87b48b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('administrator')
    with op.batch_alter_table('admin_feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_review_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('admin_feedbacks_review_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['admin_review_id'])
        batch_op.drop_constraint(batch_op.f('admin_feedbacks_review_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_reviews', ['admin_review_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('review_id')

    with op.batch_alter_table('admin_objectives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admin_objectives_assigned_to_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('admin_objectives_batch_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('admin_objectives_assigned_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'authentications', ['assigned_to_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'admin_objective_batches', ['admin_batch_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'administrators', ['assigned_by_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_objective_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('admin_reviews_objective_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['admin_objective_id'])
        batch_op.drop_constraint(batch_op.f('admin_reviews_objective_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_objectives', ['admin_objective_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('objective_id')

    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.alter_column('authentication_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('administrators_authentication_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'authentications', ['authentication_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('departments_administrator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'administrators', ['administrator_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('authentication_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('employees_department_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('employees_authentication_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'authentications', ['authentication_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('feedbacks_review_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reviews', ['review_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('objectives_batch_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('objectives_assigned_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('objectives_assigned_to_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'team_leaders', ['assigned_by_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'authentications', ['assigned_to_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'objective_batches', ['batch_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('objective_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('reviews_objective_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'objectives', ['objective_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('team_leaders', schema=None) as batch_op:
        batch_op.alter_column('authentication_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('team_leaders_department_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('team_leaders_authentication_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'authentications', ['authentication_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_leaders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_leaders_authentication_id_fkey'), 'authentications', ['authentication_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('team_leaders_department_id_fkey'), 'departments', ['department_id'], ['id'])
        batch_op.alter_column('authentication_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_objective_id_fkey'), 'objectives', ['objective_id'], ['id'])
        batch_op.alter_column('objective_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('objectives_assigned_to_id_fkey'), 'authentications', ['assigned_to_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('objectives_assigned_by_id_fkey'), 'team_leaders', ['assigned_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('objectives_batch_id_fkey'), 'objective_batches', ['batch_id'], ['id'])

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedbacks_review_id_fkey'), 'reviews', ['review_id'], ['id'])
        batch_op.alter_column('review_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('employees_authentication_id_fkey'), 'authentications', ['authentication_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('employees_department_id_fkey'), 'departments', ['department_id'], ['id'])
        batch_op.alter_column('authentication_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('departments_administrator_id_fkey'), 'administrators', ['administrator_id'], ['id'])

    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('administrators_authentication_id_fkey'), 'authentications', ['authentication_id'], ['id'])
        batch_op.alter_column('authentication_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_reviews_objective_id_fkey'), 'admin_objectives', ['objective_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('admin_reviews_objective_id_key'), ['objective_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('admin_objective_id')

    with op.batch_alter_table('admin_objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_objectives_assigned_by_id_fkey'), 'administrator', ['assigned_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admin_objectives_batch_id_fkey'), 'admin_objective_batches', ['batch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admin_objectives_assigned_to_id_fkey'), 'authentications', ['assigned_to_id'], ['id'])

    with op.batch_alter_table('admin_feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_feedbacks_review_id_fkey'), 'admin_reviews', ['review_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('admin_feedbacks_review_id_key'), ['review_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('admin_review_id')

    op.create_table('administrator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('authentication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], name=op.f('administrator_authentication_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('administrator_pkey')),
    sa.UniqueConstraint('authentication_id', name=op.f('administrator_authentication_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
