"""make department not null

Revision ID: 45b20da64cb3
Revises: 10bf2548a6c2
Create Date: 2026-01-16 02:11:28.566158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b20da64cb3'
down_revision = '10bf2548a6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('employee_emails_department_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('employee_emails_role_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('employee_emails_role_key'), ['role'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('employee_emails_department_key'), ['department'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
