"""add role

Revision ID: 4cc00415a389
Revises: ceb5c8d6b3cf
Create Date: 2026-01-16 01:00:37.559444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc00415a389'
down_revision = 'ceb5c8d6b3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint(None, ['role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
