"""add duration

Revision ID: 885a49552517
Revises: ccc0f9b63da7
Create Date: 2026-04-11 01:34:00.925593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885a49552517'
down_revision = 'ccc0f9b63da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective_batches', schema=None) as batch_op:
        batch_op.drop_column('deadline')
        batch_op.drop_column('created_at')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
