"""initial

Revision ID: 89a198233d79
Revises: 
Create Date: 2026-01-14 10:51:49.224111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a198233d79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_objective_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authentications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('objective_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id')
    )
    op.create_table('admin_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('score_range', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('admin_batch_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_batch_id'], ['admin_objective_batches.id'], ),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['administrator.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['authentications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('admin_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_objective_id'], ['admin_objectives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_objective_id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id')
    )
    op.create_table('team_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id'),
    sa.UniqueConstraint('dept_id')
    )
    op.create_table('admin_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('score_range', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['team_leaders.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['authentications.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['objective_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objective_id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    op.drop_table('reviews')
    op.drop_table('objectives')
    op.drop_table('admin_feedbacks')
    op.drop_table('team_leaders')
    op.drop_table('employees')
    op.drop_table('admin_reviews')
    op.drop_table('departments')
    op.drop_table('admin_objectives')
    op.drop_table('administrator')
    op.drop_table('objective_batches')
    op.drop_table('authentications')
    op.drop_table('admin_objective_batches')
    # ### end Alembic commands ###
