"""add score

Revision ID: 8f17b02a0ed4
Revises: b1c7431cfea8
Create Date: 2026-04-20 10:08:36.483065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f17b02a0ed4'
down_revision = 'b1c7431cfea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_reviewed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_reviewed', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
