"""Admin review feedback models renamed

Revision ID: 9818fd5c6370
Revises: 35832c68ed40
Create Date: 2026-01-15 05:51:58.630682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9818fd5c6370'
down_revision = '35832c68ed40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_review_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.create_table('team_leader_admin_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.create_table('team_leader_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.drop_table('administrator')
    op.drop_table('admin_feedbacks')
    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('admin_reviews_admin_objective_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_objectives', ['admin_objective_id'], ['id'])
        batch_op.drop_column('weighted_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weighted_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_reviews_admin_objective_id_fkey'), 'admin_objectives', ['admin_objective_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('review',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('created_at')

    op.create_table('admin_feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], name=op.f('admin_feedbacks_admin_review_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_feedbacks_pkey')),
    sa.UniqueConstraint('admin_review_id', name=op.f('admin_feedbacks_admin_review_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('administrator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('authentication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], name=op.f('administrator_authentication_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('administrator_pkey')),
    sa.UniqueConstraint('authentication_id', name=op.f('administrator_authentication_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('team_leader_feedbacks')
    op.drop_table('team_leader_admin_feedback')
    op.drop_table('admin_review_feedback')
    # ### end Alembic commands ###
