"""add active

Revision ID: 98eb88a55c2e
Revises: b592efc358aa
Create Date: 2026-04-29 09:01:05.286780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98eb88a55c2e'
down_revision = 'b592efc358aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective_batches', schema=None) as batch_op:
        batch_op.drop_column('start')
        batch_op.drop_column('end')

    # ### end Alembic commands ###
