"""fixed models

Revision ID: 9dd4a87b48b2
Revises: 89a198233d79
Create Date: 2026-01-14 13:56:40.751427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd4a87b48b2'
down_revision = '89a198233d79'
branch_labels = None
depends_on = None


def upgrade():
    # IMPORTANT:
    # We DO NOT drop the old administrator table
    # because it is referenced by multiple foreign keys.
    # Instead, we keep it and migrate relationships safely.

    # 1. Create administrators table ONLY if it does not exist
    # (comment this out if administrators already exists)
    op.create_table(
        'administrators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('authentication_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('authentication_id')
    )

    # ❌ DO NOT DROP administrator
    # op.drop_table('administrator')

    # ---- ADMIN FEEDBACK FIX ----
    with op.batch_alter_table('admin_feedbacks') as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(
            batch_op.f('admin_feedbacks_admin_review_id_fkey'),
            type_='foreignkey'
        )
        batch_op.drop_constraint(
            batch_op.f('admin_feedbacks_admin_review_id_key'),
            type_='unique'
        )
        batch_op.create_foreign_key(
            None, 'admin_reviews', ['review_id'], ['id']
        )
        batch_op.create_unique_constraint(None, ['review_id'])
        batch_op.drop_column('admin_review_id')

    # ---- ADMIN OBJECTIVES FIX ----
    with op.batch_alter_table('admin_objectives') as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f('admin_objectives_admin_batch_id_fkey'),
            type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None, 'admin_objective_batches', ['batch_id'], ['id']
        )

    # ---- ADMIN REVIEWS FIX ----
    with op.batch_alter_table('admin_reviews') as batch_op:
        batch_op.add_column(sa.Column('objective_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(
            batch_op.f('admin_reviews_admin_objective_id_fkey'),
            type_='foreignkey'
        )
        batch_op.drop_constraint(
            batch_op.f('admin_reviews_admin_objective_id_key'),
            type_='unique'
        )
        batch_op.create_foreign_key(
            None, 'admin_objectives', ['objective_id'], ['id']
        )
        batch_op.create_unique_constraint(None, ['objective_id'])
        batch_op.drop_column('admin_objective_id')

    # ---- DEPARTMENTS FIX ----
    with op.batch_alter_table('departments') as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ---- EMPLOYEES FIX ----
    with op.batch_alter_table('employees') as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f('employees_dept_id_fkey'),
            type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None, 'departments', ['department_id'], ['id']
        )
        batch_op.drop_column('dept_id')

    # ---- TEAM LEADERS FIX ----
    with op.batch_alter_table('team_leaders') as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f('team_leaders_dept_id_fkey'),
            type_='foreignkey'
        )
        batch_op.drop_constraint(
            batch_op.f('team_leaders_dept_id_key'),
            type_='unique'
        )
        batch_op.create_foreign_key(
            None, 'departments', ['department_id'], ['id']
        )
        batch_op.create_unique_constraint(None, ['department_id'])
        batch_op.drop_column('dept_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_leaders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_leaders_dept_id_fkey'), 'departments', ['dept_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('team_leaders_dept_id_key'), ['dept_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('department_id')

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('objectives_assigned_to_id_fkey'), 'authentications', ['assigned_to_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('employees_dept_id_fkey'), 'departments', ['dept_id'], ['id'])
        batch_op.drop_column('department_id')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('departments_administrator_id_fkey'), 'administrator', ['administrator_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_objective_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_reviews_admin_objective_id_fkey'), 'admin_objectives', ['admin_objective_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('admin_reviews_admin_objective_id_key'), ['admin_objective_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('objective_id')

    with op.batch_alter_table('admin_objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_batch_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_objectives_assigned_to_id_fkey'), 'authentications', ['assigned_to_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admin_objectives_assigned_by_id_fkey'), 'administrator', ['assigned_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admin_objectives_admin_batch_id_fkey'), 'admin_objective_batches', ['admin_batch_id'], ['id'])
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('admin_feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_feedbacks_admin_review_id_fkey'), 'admin_reviews', ['admin_review_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('admin_feedbacks_admin_review_id_key'), ['admin_review_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('review_id')

    op.create_table('administrator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('authentication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], name=op.f('administrator_authentication_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('administrator_pkey')),
    sa.UniqueConstraint('authentication_id', name=op.f('administrator_authentication_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('administrators')
    # ### end Alembic commands ###
