"""add authreviewed

Revision ID: b1c7431cfea8
Revises: de61c918fe98
Create Date: 2026-04-19 21:52:36.922829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c7431cfea8'
down_revision = 'de61c918fe98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_reviewed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_objective_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'admin_objectives', ['admin_objective_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'objectives', ['objective_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_reviewed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_objective_id')
        batch_op.drop_column('objective_id')

    # ### end Alembic commands ###
