"""add active

Revision ID: b592efc358aa
Revises: acb5a63e5017
Create Date: 2026-04-28 11:23:51.114374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b592efc358aa'
down_revision = 'acb5a63e5017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective_batches', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
