"""remove nullable

Revision ID: d861cd12c248
Revises: 1d1b5fe98b4f
Create Date: 2026-04-15 08:44:06.344949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd861cd12c248'
down_revision = '1d1b5fe98b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('objective_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('admin_objective_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('admin_objective_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('objective_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
