"""add auth reviewed

Revision ID: de61c918fe98
Revises: 08ec58a25884
Create Date: 2026-04-19 17:36:49.814726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de61c918fe98'
down_revision = '08ec58a25884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_reviewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_reviewed')
    # ### end Alembic commands ###
