"""initial migration

Revision ID: e3b39aca56bc
Revises: 
Create Date: 2026-05-26 11:35:16.293067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b39aca56bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('objective_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id')
    )
    op.create_table('admin_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('score_range', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['administrators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['objective_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('admin_objective_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_objective_id'], ['admin_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_objective_id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id')
    )
    op.create_table('team_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id'),
    sa.UniqueConstraint('department_id')
    )
    op.create_table('admin_review_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('score_range', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['team_leaders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['objective_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_leader_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.create_table('auth_reviewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('admin_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_objective_id'], ['admin_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auth_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('admin_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_objective_id'], ['admin_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewopenobjectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('number_reviews', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('admin_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_objective_id'], ['admin_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_objective_id'),
    sa.UniqueConstraint('objective_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objective_id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    op.drop_table('reviews')
    op.drop_table('reviewopenobjectives')
    op.drop_table('messages')
    op.drop_table('auth_reviewed')
    op.drop_table('team_leader_feedbacks')
    op.drop_table('objectives')
    op.drop_table('admin_review_feedbacks')
    op.drop_table('team_leaders')
    op.drop_table('employees')
    op.drop_table('admin_reviews')
    op.drop_table('departments')
    op.drop_table('admin_objectives')
    op.drop_table('administrators')
    op.drop_table('objective_batches')
    op.drop_table('employee_emails')
    op.drop_table('authentications')
    # ### end Alembic commands ###
