"""Fix admin review feedback models

Revision ID: e90014e2126f
Revises: 9818fd5c6370
Create Date: 2026-01-15 06:13:58.080013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e90014e2126f'
down_revision = '9818fd5c6370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_review_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.create_table('team_leader_admin_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=False),
    sa.Column('admin_review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_review_id')
    )
    op.drop_table('admin_review_feedback')
    op.drop_table('team_leader_admin_feedback')
    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weighted_score', sa.Float(), nullable=False))
        batch_op.alter_column('review',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('admin_reviews_admin_objective_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_objectives', ['admin_objective_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_reviews_admin_objective_id_fkey'), 'admin_objectives', ['admin_objective_id'], ['id'])
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('review',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('weighted_score')

    op.create_table('team_leader_admin_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], name=op.f('team_leader_admin_feedback_admin_review_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('team_leader_admin_feedback_pkey')),
    sa.UniqueConstraint('admin_review_id', name=op.f('team_leader_admin_feedback_admin_review_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('admin_review_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_review_id'], ['admin_reviews.id'], name=op.f('admin_review_feedback_admin_review_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_review_feedback_pkey')),
    sa.UniqueConstraint('admin_review_id', name=op.f('admin_review_feedback_admin_review_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('team_leader_admin_feedbacks')
    op.drop_table('admin_review_feedbacks')
    # ### end Alembic commands ###
