"""add open

Revision ID: ec9a543004e6
Revises: d861cd12c248
Create Date: 2026-04-19 11:50:01.257037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9a543004e6'
down_revision = 'd861cd12c248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewopenobjectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('admin_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_objective_id'], ['admin_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_objective_id'),
    sa.UniqueConstraint('objective_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewopenobjectives')
    # ### end Alembic commands ###
